import Head from "next/head";
import styles from "../styles/Acceuil.module.css";
import Header from "@/components/Header";
 
 
export default function Home() {
  const submitForm = (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const formDataObject = {};
    formData.forEach((value, key) => {
      formDataObject[key] = value;
    });
    console.log(formDataObject);
    // Ajoutez ici le code pour traiter les données du formulaire
  };
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <h1 className={styles.titre}>Formulaire Patient</h1>
        <form onSubmit={submitForm} className={styles.form}>
          <div>
            <label htmlFor="prenom">Prénom :</label>
            <input type="text" id="prenom" name="prenom" required />
          </div>
          <div>
            <label htmlFor="nom">Nom :</label>
            <input type="text" id="nom" name="nom" required />
          </div>
         
          <div>
            <label htmlFor="dateNaissance">Date de Naissance :</label>
            <input type="date" id="dateNaissance" name="dateNaissance" required />
          </div>
          <div>
            <label htmlFor="email">E-mail :</label>
            <input type="email" id="email" name="email" required />
          </div>
          <div>
            <label htmlFor="adresse">Adresse :</label>
            <textarea id="adresse" name="adresse" required></textarea>
          </div>
          <div>
            <label htmlFor="numAssurance">Numéro d'Assurance :</label>
            <input type="text" id="numAssurance" name="numAssurance" required />
          </div>
          <div>
            <label htmlFor="numTelephone">Numéro de Téléphone :</label>
            <input type="tel" id="numTelephone" name="numTelephone" required />
          </div>
          <div>
            <label htmlFor="numUrgence">Numéro d'Urgence :</label>
            <input type="tel" id="numUrgence" name="numUrgence" required />
          </div>
          <div>
            <label htmlFor="prenomUrgence">Personne d'urgence :</label>
            <input type="text" id="prenom" name="prenom" required />
          </div>
          <div>
          <label>Relation : </label>
          <select name="Relation" >
            <option value="">Choisir...</option>
            <option value="homme">Frère</option>
            <option value="femme">Soeur</option>
            <option value="parent">Parent</option>
            <option value="amie">Ami(e)s</option>
          </select>
        </div>
          <div>
            <label htmlFor="description">Description :</label>
            <textarea id="description" name="description" required></textarea>
          </div>
          <button type="submit" className={styles.button}>Soumettre</button>
        </form>
      </main>
    </>
  );
}