
import Aside from "@/components/Aside";
import Header from "@/components/Header";
import AsideDocteur from "@/components/aside/AsideDocteur";
import DR_Acceuil from "@/components/contents/dr/DR_Acceuil";
import DR_Content from "@/components/contents/dr/DR_Content";
import Head from "next/head";
import { useState } from "react";



export default function Ressource() {
  const [content, setContent] = useState(<DR_Acceuil />);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Aside setContent={setContent} asideContent={<AsideDocteur />} />
      <DR_Content content={content}/>
      
    </>
  );
}
