import Aside from "@/components/Aside";
import Header from "@/components/Header";
import AsideDocteur from "@/components/aside/AsideDocteur";
import DR_Acceuil from "@/components/contents/dr/DR_Acceuil";
import DR_Content from "@/components/contents/dr/DR_Content";
import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import { routes } from "./services/routes.js";
import { useEffect } from "react";

export default function Ressource() {
  const router = useRouter();
  const { pathname } = router;

  const [content, setContent] = useState(<DR_Acceuil />);
  const [visible, setVisible] = useState(false);
  const [titre, setTitre] = useState('Accueil');
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login");
    } else {
      const user = JSON.parse(token);
      const route_user = routes(user.id_role);
      if (pathname !== route_user) {
        router.push(route_user);
      } else {
        setVisible(true);
      }
    }
  }, []);
  return (
    <>
      {visible ? (
        <>
          <Head>
            <title>docteur - {titre} </title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header />
          <Aside  asideContent={<AsideDocteur  setContent={setContent} setTitre={setTitre}/>} />
          <DR_Content content={content} />
        </>
      ):(null)}
    </>
  );
}
