
import Aside from "@/components/Aside";
import Header from "@/components/Header";
import INF_Accueil from "@/components/contents/inf/INF_Accueil";
import INF_Content from "@/components/contents/inf/INF_Content";
import Head from "next/head";
import { useState } from "react";


export default function Ressource() {
  const [content, setContent] = useState(<INF_Accueil />);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Aside setContent={setContent} role={5}/>
      <INF_Content content={content}/>

      
    </>
  );
}
