
import Aside from "@/components/Aside";
import Header from "@/components/Header";
import Laboratoire_Accueil from "@/components/contents/Labo/Laboratoire_Accueil";
import Labo_Content from "@/components/contents/Labo/Labo_Content";
import Head from "next/head";
import { useState } from "react";
import AsideLaborantins from "@/components/aside/AsideLaborantins";




export default function Ressource() {
  const [content, setContent] = useState(<Laboratoire_Accueil/>);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Aside setContent={setContent} asideContent={<AsideLaborantins/>} />
      <Labo_Content content={content}/>

      
    </>
  );
}
