import Head from "next/head";

export default function Login() {
  const soumettre = (e) => {
    e.preventDefault();
    console.log(e.target.numeroEmployer.value, e.target.password.value);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Login</h1>
        </div>
        <div>
          <form onSubmit={soumettre}>
            <div>
              <label htmlFor="numeroEmployer">Numero Employé</label>
              <input
                type="text"
                id="numeroEmployer"
                name="numeroEmployer"
                required
              />
            </div>
            <div>
              <label htmlFor="password">Mot de passe</label>
              <input
                type="text"
                id="password"
                name="password"
                required
              />
            </div>
            <button type="submit">Se connecter</button>
          </form>
        </div>
      </main>
    </>
  );
}
