
import Aside from "@/components/Aside";
import Header from "@/components/Header";
import RH_Content from "@/components/contents/rh/RH_Content";
import RH_Accueil from "@/components/contents/rh/RH_Accueil";
import AsideRessource from "@/components/aside/AsideRessource";
import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import { routes } from "./services/routes.js";
import { useEffect } from "react";


export default function Ressource() {
  const [content, setContent] = useState(<RH_Accueil />);
  const router = useRouter();
  const { pathname } = router;

  
  const [visible, setVisible] = useState(false);
  const [titre, setTitre] = useState('Ressource');
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login");
    } else {
      const user = JSON.parse(token);
      const route_user = routes(user.id_role);
      if (pathname !== route_user) {
        router.push(route_user);
      } else {
        setVisible(true);
      }
    }
  }, []);
  return (
    <>
      {visible ? (
        <>
          <Head>
            <title>Ressource - {titre}</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header />
          <Aside  asideContent={<AsideRessource setContent={setContent} setTitre={setTitre}/>} />
          <RH_Content content={content}/>
        </>
      ):(null)}
    </>
  );
}



