
import Aside from "@/components/Aside";
import Header from "@/components/Header";
import AsideTriage from "@/components/aside/AsideTriage";
import Triage_Acceuil from "@/components/contents/triage/Triage_Acceuil";
import Triage_Content from "@/components/contents/triage/Triage_Content";
import Head from "next/head";
import { useState } from "react";


export default function Ressource() {
  const [content, setContent] = useState(<Triage_Acceuil />);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Aside setContent={setContent} asideContent={<AsideTriage />} />
      <Triage_Content content={content}/>
      

      
    </>
  );
}
